### ISSUE TITLE
Implementation Help

### ISSUE THREAD

**Issue by CommandBuffer** [TwinFan/XPMP2#1]
Hello,

I'm having some troubles with this implementation. I have sub-classed the `XPMP2::Aircraft` class through `MyAirplane` class. 

```
class MyAirplane : public Aircraft
{
public:
    MyAirplane(const std::string& _icaoType,
        const std::string& _icaoAirline,
        const std::string& _livery,
        const std::string& _modelName = "") :
    Aircraft(_icaoType, _icaoAirline, _livery, _modelName)
    {
		
    }

    virtual void UpdatePosition()
    {
        SetLocation(Position.lat, Position.lon, Position.elevation);

        drawInfo.heading = Position.heading;
        drawInfo.pitch = Position.pitch;
        drawInfo.roll = Position.roll;
    }

    XPMPPlanePosition_t Position;
};
```

Currently, I'm using a `std::map` to hold the `MyAirplane` objects. The issue I'm having is that any object that is inserted into my map is almost immediately destructed through the within `XPMP2::Aircraft`. I am able to see this because I implemented the `CBPlaneNotifier` and each aircraft object is created and then destroyed.

Am I going about this the wrong way? If so, what is the best way to keep a collection of planes so that I can update them?
```
std::map<std::string, MyAirplane*> m_Planes;

MyAirplane *aircraft = new MyAirplane(typeCode, airlineIcao, liveryStr, modelStr);
m_Planes.emplace(key, aircraft); // key is the aircraft's callsign/tailnumber
```

**Comment by TwinFan** [comment]
So why don't you just place a breakpoint in your `CBPlaneNotifier` and find out what causes the object to be destructed by looking at the call stack?

Under normal circumstance, a plane would be destroyed when the object is destroyed. So you are basically asking: Why got my object destroyed?

I cannot provide implementation support at this basic level of how to use C++ containers, sorry. There are good tutorials out there on object creation, destruction, container usage and emplacing object in them. Just google a bit.

A few hints to start with, though:
- Start with the XPMP2-Sample application. Compile, make it run, debug through it step by step to understand how it works, then remove the code you don't need and start building your own.
- The code you pasted does not at all destroy the object that `aircraft` points to. You are using unsafe pointers (as oppsed to smart pointers) and place that unsafe pointer in a map. The map does not actually manage the object. Even if the map would be destroyed the created `MyAirplane` object would not.
- Either, there is somewhere an explicit call to `delete aircraft;` or the plane is destroyed because of an other fatal event, like e.g. deactivating the library. You'll find out by debugging (first sentence).
- You should set a log level of DEBUG (see sample app, line 112), then XPMP2 will provide you with a lot of into in `Log.txt`. Would have been helpful here to look into `Log.txt`.
- Why do you bother using pointers in the first place? Consider placing the actual object into the map instead of a pointer (`std::map<std::string, MyAirplane>`, without the `*`).

Good luck!
