### ISSUE TITLE
Engines don't rotate in Sample Plugin

### ISSUE THREAD

**Issue by parlock** [TwinFan/XPMP2#14]
**Describe the bug**
Engines don't rotate in the sample plugin code.  I am on XP 11.5 with Vulkan.

**To Reproduce / Source Code Example**
Build Sample plugin and install in XP 11.5 and set it to Vulkan drivers.

**Expected behavior**
Engines/Props would rotate on the aircraft in front of me doing circles.

**Version**
 - OS: Win 10
 - X-Plane: 11.5 Vulkan

**Comment by parlock** [comment]
Tried it in 11.50b11 with either Vulkan or OpenGL.  no rotation of the engines/props in the sample plugin...

**Comment by parlock** [comment]
Solved the issue. Turns out you have to run the CSL2XSB.py on the models.  then they fully work in game with all animations...  :)

**Comment by TwinFan** [comment]
Oh, would I love self-closing issues ;-)
But in fact there is one thing to it: The documentation has
- [ ] a non working link from the README.md to the ["How to"](https://twinfan.github.io/XPMP2/HowTo.html#sample-plugin)
- [ ] and that "How to" doesn't mention the [CSL2XSB conversion](https://github.com/TwinFan/CSL2XSB) for the purpose of rotating props, that's hidden [one link further down](https://twinfan.github.io/XPMP2/Deploying.html#csl-models).
So this issue is not a coding issue, true, but a documentation issue. And for that reason re-opened.
