### ISSUE TITLE
Add a get function for the Matched Model icao type code

### ISSUE THREAD

**Issue by markcellis** [TwinFan/XPMP2#15]
If XPMP2 matches to a different ICAO type code than what was requested it would be good for the client code to see what it matched to. I could use this to play the appropriate engine audio files.

There is currently and accessor for the model name that was matched but not for the icao type code.

**Alternatives**
A fully defined pointer to the cslModel would work too. Unfortunately that is just a forward declare in the end user header files

**Benefits**
See above

**Comment by TwinFan** [comment]
Is solved by implementing `Aircraft::GetModelinfo()`, which returns a public structure with all copyable information.
The internal structure will not be published as it includes many technical implementation details and I don't want public headers to change just because of some internal tweaks. Happens too often for XPMPAircraft.h already.
