### ISSUE TITLE
Issue on CMake on macos when XPMP2 is subdir

### ISSUE THREAD

**Issue by Artemia76** [TwinFan/XPMP2#2]
Hello, I'm working to change your version of libxplanemp for your new XPMP2 for my FF2Play project.
It works fine on win and linux.
On macos , the cmake try to find ../Info.plist on build folder.
Because my project use XPMP2 as a git submodule and CMakeList.txt use add_subdirectory and link directly to the XPMP2 lib.

[https://bitbucket.org/FFS2/xffs2play/src/3c35645a9c8cdc19c0ac932d590fefcba002cf23/CMakeLists.txt#lines-101](url)

I success to build by replacing "../Info.plist"  by ${CMAKE_CURRENT_SOURCE_DIR}/Info.plist in your CMakeList.txt 

anyway many thanks for yours works, the lib works fine with the last Xplane beta ;-)

**Comment by TwinFan** [comment]
I'm not sure what you ask me to do...if you ask me to do anything. The link you provided, opens in my case just an issue search on github...ah wait...the link doesn't point to where the text says it goes...very dangerous...copying the text (instead of clicking on it) opens _your_ CMake list.

So...what do you ask for? I can certainly consider changing `../Info.plist` into `${CMAKE_CURRENT_SOURCE_DIR}/Info.plist`. Is that what you suggest to try?

**Comment by Artemia76** [comment]
Yes, the link I provided is my using context. has I use your library in subdir git submodule dependency , I ask you to replace your "../Info.plist" by "${CMAKE_CURRENT_SOURCE_DIR}/Info.plist" . The goal is to avoid me to patch your CMakeList each time I pull your repository on my mac portage.
